notes_dir="${HOME}/Notes"
tasks_dir="${HOME}/Notes/Tasks"
archive_dir="${HOME}/Notes/Archive"
scripts_dir="${HOME}/Projects/scripts"
editor="vim"

coder="coder:latest"
coder_modelfile="${HOME}/Projects/llm-prompts/Modelfile-coder"

helper="helper:latest"
helper_modelfile="${HOME}/Projects/llm-prompts/Modelfile-helper"
