notes_dir="${HOME}/Notes"
tasks_dir="${HOME}/Notes/Tasks"
archive_dir="${HOME}/Notes/Archive"
scripts_dir="${HOME}/Projects/scripts"
editor="vim"
skip_flatpak=true

# TODO: Add a flag for force using local?
# Ollama host URL or IP; for fully local, leave empty or comment out
ollama_remote_host="192.168.0.1234"

search="assistant:researcher"
search_modelfile="${HOME}/path-to/Modelfile-researcher"

helper="assistant:helper"
helper_modelfile="${HOME}/path-to/Modelfile-helper"

# display monitors (run `yo d list` to find available)
secondary=HDMI-1
main=HDMI-0
internal=eDP-1-1
